spring:
  application:
    name: Appli
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5433/tpspring
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
